DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE FACTURAS CASCADE CONSTRAINTS;
DROP TABLE LINEA_FACTURAS CASCADE CONSTRAINTS;
DROP TABLE BIENES CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE UTILIZADOS CASCADE CONSTRAINTS;

CREATE TABLE CLIENTES (
    tId VARCHAR2(50) NOT NULL,
    nId VARCHAR2(10) NOT NULL,
    nombre VARCHAR2(20) NOT NULL,
    correo VARCHAR2(10) UNIQUE,
    telefonos VARCHAR2(10) NOT NULL
);
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (tid, nid);

CREATE TABLE FACTURAS(
   numero   NUMBER PRIMARY KEY,
    fecha   DATE            NOT NULL,
    total   NUMBER(15,2)    NOT NULL
);

CREATE TABLE BIENES(
    codigo          VARCHAR2(5)     NOT NULL,
    nombre          VARCHAR2(10)    NOT NULL,
    precioVenta     NUMBER(15,2)    NOT NULL,  
    tipo VARCHAR2(10)
);

CREATE TABLE UTILIZADOS (
    servicio_codigo VARCHAR2(5)  NOT NULL,
    producto_codigo VARCHAR2(5)  NOT NULL,
    unidades        NUMBER       NOT NULL
);
    
CREATE TABLE PRODUCTOS (
    codigo       VARCHAR2(5)     NOT NULL,
    existencias  NUMBER          NOT NULL,
    precioCompra NUMBER(15,2)    NOT NULL
);

CREATE TABLE SERVICIOS (
    codigo      VARCHAR2(5)     NOT NULL,
    manoDeObra  NUMBER(15,2)    NOT NULL,
    costo       NUMBER(15,2)    NOT NULL
);

CREATE TABLE LINEA_FACTURAS (
    factura_numero  NUMBER          NOT NULL,
    bien_codigo     VARCHAR2(5)     NOT NULL,
    cantidad        NUMBER          NOT NULL,
    precioVenta     NUMBER(15,2)    NOT NULL
);
